### ISSUE TITLE
Clarification `Specification Url/Path` and `Implementation file Url/Path` field

### ISSUE THREAD

**Issue by eks-99th** [elisa-tech/BASIL#46]
Hello @pellecchialuigi 
I attended your presentation at the OSS and decided to give BASIL a try. However, I’m encountering some confusion regarding the fields "Specification URL/Path (plain text format)" and "Implementation File URL/Path".

From my understanding, these fields should point to the specification and implementation files respectively, but I’m unsure of where these files should be located. Should they be inside the app or API containers? On the host machine? Or hosted externally, such a link to a GitHub page that opens the source?

Additionally, how should I define the paths for files that are stored locally on my host machine where the containers are running? For example, if I have my_spec.txt and my_implementation.cpp on my local machine, how should I correctly fill in the "Specification URL/Path" and "Implementation File URL/Path" fields to map these files?

Thank you for your help! And congratulations for the project.

**Comment by pellecchialuigi** [comment]
Hi,
I already have a plan to work on instructional videos.

About tool potential, you may consider to:
* Use BASIL as your test execution framework (using tmt to describe your tests)
* Use work items life cycle (Review, Approval)
* Enable notifications in app at components level
* Use multiple Mapping Views to have different teams working in parallel
* User permissions at software component level
* Preview the effect of changes on mapping moving to a new version of the specifications
* Use the HTTP api to integrate BASIL in your CI

Let me know if you want to learn more about any aspects. I can prioritize content to be described in the next video.

Thanks once again
