### ISSUE TITLE
Licence incompatibility

### ISSUE THREAD

**Issue by brejoc** [elisa-tech/BASIL#7]
As far as I know, the GPLv2 is incompatible with the Apache Software License version 2.0. requests is using Apache v2 for their licence.
We could switch to GPLv3, which is compatible with Apache v2, or remove requests as a dependency. 

https://gplv3.fsf.org/wiki/index.php/Compatible_licenses

**Comment by pellecchialuigi** [comment]
@paolonig do you have any opinion about that?

**Comment by paolonig** [comment]
@brejoc  are you sure that we need a compatible license from the BASIL  point of view if BASIL is just invoking requests commands ? I thought that we'd have licenses issues if we were going to clone and modify requests source code (e.g. to have a custom version of such a library)..... ?

**Comment by brejoc** [comment]
If you modify the source code or not doesn't matter. What matters more is the distribution. I don't know what the plans for Basil are in that regard. Maybe if it isn't shipped as product that's okay. We can check with legal.

**Comment by paolonig** [comment]
Ok' let's sync internally and then evaluate how to follow-up on this issue.

**Comment by brejoc** [comment]
Since we'll be sticking to source distribution we won't have a problem here and we can close the issue. If at some point of time a packaged distribution becomes interesting, we'll have to revisit this again. Thanks everybody!
